version: '3.8'
services:
    web:
        build: .
        env_file:
            - .env
        ports:
        - "8000:3000"
        volumes:
        - .:/usr/src/app
        expose:
        - "8000"
        command: air main.go -b 0.0.0.0
    mysql:
        image: mysql
        container_name: mysql
        # env_file: # using env file instead of env variables
        #     - database.env 
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            # So you don't have to use root, but you can if you like
            MYSQL_USER: ${DB_USER}
            # You can use whatever password you like
            MYSQL_PASSWORD: ${DB_PASSWORD}
            # Password for root access
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: '%'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '5972:3306'
        expose:
            # Opens port 3306 on the container
            - '5972'
        # Where our data will be persisted
        volumes:
            - my-db-data:/var/lib/mysql
        restart: always

# Names our volume
volumes:
    my-db-data:  # named volumes can be managed easier using docker-compose