version: '3.3'
services:
    mysql:
        image: mysql
        container_name: mysql
        # env_file: # using env file instead of env variables
        #     - database.env 
        environment:
            MYSQL_DATABASE: 'go-react-app'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'liberi'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'liberi'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'liberi'
            MYSQL_ROOT_HOST: '%'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '88972:3306'
        expose:
            # Opens port 3306 on the container
            - '88972'
        # Where our data will be persisted
        volumes:
            - my-db-data:/var/lib/mysql
        restart: always

# Names our volume
volumes:
    my-db-data:
    mongodb_data_container:
    pg-db-data: # named volumes can be managed easier using docker-compose