version: '3.8'
services:
    web:
        build: backend/
        ports:
        - "8000:3000"
        volumes:
        - ./backend:/usr/src/app
        expose:
        - "8000"
        command: air main.go -b 0.0.0.0
        depends_on:
        - mysql
    mysql:
        image: mysql
        container_name: mysql
        env_file: # using env file instead of env variables
            - backend/.env
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '5972:3306'
        expose:
            # Opens port 3306 on the container
            - '5972'
        # Where our data will be persisted
        volumes:
            - my-db-data:/var/lib/mysql
        restart: always
    frontend:
        build: frontend
        ports:
        - "3000:5173"
        volumes:
        - ./frontend:/app
        - /app/node_modules
        command: ["yarn", "dev"]
        environment:
        - HOST=0.0.0.0
        depends_on:
        - web
        links:
        - web

# Names our volume
volumes:
    my-db-data:  # named volumes can be managed easier using docker-compose